import type { TestCardDefinition } from './catalog.js';

/**
 * The built-in catalog. Two families are provided:
 *
 * - Stripe-familiar numbers, so existing test suites written against Stripe test mode keep working.
 *   Their behavior is LocalStripe's own definition and may differ in details from Stripe.
 * - The LocalStripe `4242 4242 4242 000X` series, which exists only here. These numbers are
 *   deliberately not Luhn-valid, so they can never be a real card number.
 */
export const DEFAULT_TEST_CARDS: TestCardDefinition[] = [
  {
    id: 'visa_success',
    number: '4242424242424242',
    brand: 'visa',
    label: 'Visa — succeeds',
    scenario: 'succeeded',
    payment_method_token: 'pm_card_visa',
    description: 'Payment succeeds immediately.',
  },
  {
    id: 'visa_debit_success',
    number: '4000056655665556',
    brand: 'visa',
    funding: 'debit',
    label: 'Visa (debit) — succeeds',
    scenario: 'succeeded',
    payment_method_token: 'pm_card_visa_debit',
    description: 'Debit card; payment succeeds immediately.',
  },
  {
    id: 'mastercard_success',
    number: '5555555555554444',
    brand: 'mastercard',
    label: 'Mastercard — succeeds',
    scenario: 'succeeded',
    payment_method_token: 'pm_card_mastercard',
    description: 'Payment succeeds immediately.',
  },
  {
    id: 'amex_success',
    number: '378282246310005',
    brand: 'amex',
    label: 'American Express — succeeds',
    scenario: 'succeeded',
    payment_method_token: 'pm_card_amex',
    description: 'Payment succeeds immediately.',
  },
  {
    id: 'generic_decline',
    number: '4000000000000002',
    brand: 'visa',
    label: 'Declined (generic_decline)',
    scenario: 'declined',
    error_code: 'card_declined',
    decline_code: 'generic_decline',
    payment_method_token: 'pm_card_chargeDeclined',
    description: 'Payment is declined with card_declined / generic_decline.',
  },
  {
    id: 'insufficient_funds',
    number: '4000000000009995',
    brand: 'visa',
    label: 'Declined (insufficient_funds)',
    scenario: 'declined',
    error_code: 'card_declined',
    decline_code: 'insufficient_funds',
    payment_method_token: 'pm_card_chargeDeclinedInsufficientFunds',
    description: 'Payment is declined with card_declined / insufficient_funds.',
  },
  {
    id: 'expired_card',
    number: '4000000000000069',
    brand: 'visa',
    label: 'Declined (expired_card)',
    scenario: 'declined',
    error_code: 'expired_card',
    decline_code: 'expired_card',
    payment_method_token: 'pm_card_chargeDeclinedExpiredCard',
    description: 'Payment is declined with expired_card.',
  },
  {
    id: 'incorrect_cvc',
    number: '4000000000000127',
    brand: 'visa',
    label: 'Declined (incorrect_cvc)',
    scenario: 'declined',
    error_code: 'incorrect_cvc',
    decline_code: 'incorrect_cvc',
    payment_method_token: 'pm_card_chargeDeclinedIncorrectCvc',
    description: 'Payment is declined with incorrect_cvc.',
  },
  {
    id: 'processing_error',
    number: '4000000000000119',
    brand: 'visa',
    label: 'Declined (processing_error)',
    scenario: 'declined',
    error_code: 'processing_error',
    decline_code: 'processing_error',
    payment_method_token: 'pm_card_chargeDeclinedProcessingError',
    description: 'Payment fails with processing_error.',
  },
  {
    id: 'authentication_required',
    number: '4000002500003155',
    brand: 'visa',
    label: '3D Secure — authentication required',
    scenario: 'requires_action',
    payment_method_token: 'pm_card_authenticationRequired',
    description:
      'Confirmation moves the payment to requires_action. Completing the simulated 3DS challenge makes it succeed; failing it declines it.',
  },
  {
    id: 'threeds2_required',
    number: '4000000000003220',
    brand: 'visa',
    label: '3D Secure 2 — authentication required',
    scenario: 'requires_action',
    payment_method_token: 'pm_card_threeDSecure2Required',
    description: 'Same behavior as the 3155 card.',
  },
  {
    id: 'local_succeeded',
    number: '4242424242420001',
    brand: 'visa',
    label: 'LocalStripe — succeeds',
    scenario: 'succeeded',
    description: 'LocalStripe-only number. Payment succeeds.',
  },
  {
    id: 'local_declined',
    number: '4242424242420002',
    brand: 'visa',
    label: 'LocalStripe — declined',
    scenario: 'declined',
    error_code: 'card_declined',
    decline_code: 'generic_decline',
    description: 'LocalStripe-only number. Payment is declined.',
  },
  {
    id: 'local_requires_action',
    number: '4242424242420003',
    brand: 'visa',
    label: 'LocalStripe — requires 3DS',
    scenario: 'requires_action',
    description: 'LocalStripe-only number. Payment requires the simulated 3DS challenge.',
  },
  {
    id: 'local_processing',
    number: '4242424242420004',
    brand: 'visa',
    label: 'LocalStripe — processing, then succeeds',
    scenario: 'processing',
    settles_to: 'succeeded',
    description:
      'LocalStripe-only number. Confirmation returns `processing`; the payment succeeds asynchronously after the processing delay.',
  },
  {
    id: 'local_insufficient_funds',
    number: '4242424242420005',
    brand: 'visa',
    label: 'LocalStripe — insufficient funds',
    scenario: 'declined',
    error_code: 'card_declined',
    decline_code: 'insufficient_funds',
    description: 'LocalStripe-only number. Payment is declined with insufficient_funds.',
  },
  {
    id: 'local_expired_card',
    number: '4242424242420006',
    brand: 'visa',
    label: 'LocalStripe — expired card',
    scenario: 'declined',
    error_code: 'expired_card',
    decline_code: 'expired_card',
    description: 'LocalStripe-only number. Payment is declined with expired_card.',
  },
  {
    id: 'local_processing_declined',
    number: '4242424242420007',
    brand: 'visa',
    label: 'LocalStripe — processing, then fails',
    scenario: 'processing',
    settles_to: 'declined',
    error_code: 'card_declined',
    decline_code: 'generic_decline',
    description:
      'LocalStripe-only number. Confirmation returns `processing`; the payment fails asynchronously after the processing delay.',
  },
];
